### PR TITLE
Added Paging Functionality based on query parameters.

### PR DESCRIPTION
**Pull request by SpeckiJ**
Partly Implements #129 

- Adds Paging Functionality based on query Parameters `offset` and `limit`.
- Dependent on ordering of DB Output proposed in dao-series-api [PR#44](https://github.com/52North/dao-series-api/pull/44)

Specific Usage Information can be found in the docs  and in raw format at `/docs/paging.md`.

### CODE REVIEW

**Comment by ridoo** [comment]
@SpeckiJ During my tests I found some issues:

* wrong paging: for example (notice first and last links!)
```
Link: <http://localhost:9080/api/features?offset=9&limit=2> rel="self"
Link: <http://localhost:9080/api/features?offset=7&limit=2> rel="previous"
Link: <http://localhost:9080/api/features?offset=0&limit=2> rel="first"
Link: <http://localhost:9080/api/features?offset=8&limit=2> rel="last"
```
*  Error when requesting with `expanded=true`, e.g. `http://localhost:8080/api/services?platformtypes=all&limit=1&expanded=true`
```
{"statusCode":500,"developerMessage":"could not extract ResultSet","userMessage":"Unexpected Exception occured.","reason":"Internal Server Error"}
```

**Comment by SpeckiJ** [comment]
Due to the fact that the offset parameter is inherently not designed for usage as a page indicator, a problem arises when the User can freely specify the offset. The offset can be used to jump in the middle of pages, as it does not specify the Page Number, but the Number of elements on previous Pages. 

In general providing a custom offset is not encouraged, a client should **always** use the offsets provided in the response-header-links. In ideal circumstances, a client would provide only a limit in his first request, and then only follow the Response-Header-Links.

For demonstration of the Problem a query with `offset=3&limit=5` will be used.

**Problem:** 3 is not a multiple of 5, therefore building a clean Pagination is not possible.

Possible Solutions:

1. **always start a page at the provided offset + return Elements twice**. As the First Page is fixed to start with offset=0, if the offset is smaller than the limit, the first Page will overlap with the requested Page

   firstsolution
   
   **Drawback**: Up to limit-offset Elements returned twice


2. **always start a page at the provided offset + modify limit on first Page**. The First Page will be shrunk to end when the requested Page starts. the new limit for the first page can be between 1 and limit-1.

   firstsolution
   
   **Drawback**: Some Links (first, previous) in Response Header will sometimes contain the smaller limit instead of the requested one. If Client follows the Links, a new Pagination will be calculated based on the shrunk limit. In worst case scenario limit will be set to 1 and client needs to manually override limit provided by the API to recieve reasonable results
   
   
3. **build pages based on provided limit + modify/rewrite offset**. when requesting an offset that does not match n*limit, the client gets the page closest to the provided offset back. The Response Header will reflect that modification by returning the "rel=self"-Link to the Page returned (albeit not always the Page specifically requested). This ensures that the if the client always follows the Header Links the Pagination will not change.

   **Drawback**: Client does not get the specific site he requested (as the offset and limit did not fit together to build full pages)
   

4. **Only allow valid offsets**. The API could reject offsets that do not match a multiple of the limit.

   **Drawback**: no custom pagination possible. could break existing implementations.

@ridoo @autermann : With what solution shall i proceed? (Or is there another different one)

**Comment by ridoo** [comment]
@SpeckiJ thanks for detailed analysis. I've to admit that I wasn't aware of the 1st scenario you described.

What about treating `offset` as *page number* and `limit` as a *number of items per page* (have a look at [the Github pagination examples](https://developer.github.com/v3/guides/traversing-with-pagination/)). If we keep using those parameters we won't break something, as pagination hasn't been implemented so far as was documented very coarse in earlier versions anyway.

**Comment by SpeckiJ** [comment]
Modifying the semantics of the `offset`-parameter to reflect the actual page number instead of an element count would indeed be the most elegant solution.

If there are no further Objections i would implement the Modification suggested by @ridoo. I will also update the docs to reflect the changes.

**Pull request merged**
